# Generated by Django 5.0.2 on 2024-02-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
    ]
